// deepfakeAnalysisService.js
// Detects signs of AI-generated or manipulated media using:
//   1. Transcript linguistic analysis (synthetic speech patterns)
//   2. YouTube metadata signals (channel age, description patterns)
//   3. Groq LLM reasoning on combined signals
//
// No vision API or frame extraction required.
// Always returns a result — never throws (fails silently).

const axios = require('axios')

const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions'
const GROQ_MODEL   = 'llama3-8b-8192'

// ── Fetch extended YouTube metadata via oEmbed ────────────────────────────────

async function fetchVideoMetadata(videoUrl) {
  try {
    const res = await axios.get('https://www.youtube.com/oembed', {
      params: { url: videoUrl, format: 'json' },
      timeout: 6000,
    })
    return {
      title:      res.data.title       || '',
      authorName: res.data.author_name || '',
    }
  } catch {
    return null
  }
}

// ── Local heuristic: detect synthetic speech patterns in transcript ────────────
// These patterns are statistically more common in AI-generated/TTS content.

function analyzeTranscriptPatterns(transcript) {
  if (!transcript || transcript.length < 50) return { score: 0, signals: [] }

  const text    = transcript.toLowerCase()
  const signals = []
  let   score   = 0

  // 1. Unnaturally uniform sentence length (TTS tends to produce even cadence)
  const sentences = transcript.split(/[.!?]+/).filter(s => s.trim().length > 10)
  if (sentences.length >= 5) {
    const lengths = sentences.map(s => s.trim().split(/\s+/).length)
    const avg     = lengths.reduce((a, b) => a + b, 0) / lengths.length
    const variance = lengths.reduce((s, l) => s + Math.pow(l - avg, 2), 0) / lengths.length
    if (variance < 8 && avg > 8) {
      signals.push('UNIFORM_SENTENCE_RHYTHM')
      score += 15
    }
  }

  // 2. Absence of natural speech disfluencies (um, uh, like, you know)
  const disfluencies = (text.match(/\b(um|uh|like|you know|i mean|sort of|kind of|basically|actually)\b/g) || []).length
  const wordCount    = text.split(/\s+/).length
  if (wordCount > 200 && disfluencies / wordCount < 0.005) {
    signals.push('NO_SPEECH_DISFLUENCIES')
    score += 20
  }

  // 3. Overly formal / scripted language patterns
  const formalPatterns = (text.match(/\b(furthermore|moreover|in conclusion|it is important to note|it should be noted|as we can see|in this video|today we will|let us explore)\b/g) || []).length
  if (formalPatterns >= 3) {
    signals.push('SCRIPTED_FORMAL_LANGUAGE')
    score += 15
  }

  // 4. Repetitive transitional phrases (common in AI-generated scripts)
  const transitions = (text.match(/\b(moving on|next up|let's talk about|now let's|as mentioned|as i said|as we discussed)\b/g) || []).length
  if (transitions >= 4) {
    signals.push('REPETITIVE_TRANSITIONS')
    score += 10
  }

  // 5. Suspiciously perfect grammar with no contractions (TTS avoids contractions)
  const contractions = (text.match(/\b(i'm|you're|we're|they're|it's|don't|can't|won't|isn't|aren't|wasn't|weren't|i've|you've|we've|they've|i'll|you'll|we'll|they'll)\b/g) || []).length
  if (wordCount > 300 && contractions / wordCount < 0.01) {
    signals.push('ABSENCE_OF_CONTRACTIONS')
    score += 15
  }

  // 6. AI-generated content disclosure phrases
  if (/\b(generated by ai|ai generated|created with ai|made with artificial intelligence|this video was created)\b/i.test(transcript)) {
    signals.push('AI_DISCLOSURE_DETECTED')
    score += 40
  }

  // 7. Voice cloning / deepfake keywords in title or transcript
  if (/\b(deepfake|voice clone|ai voice|synthetic voice|text.?to.?speech|tts|eleven.?labs|murf|replica)\b/i.test(transcript)) {
    signals.push('SYNTHETIC_VOICE_KEYWORDS')
    score += 30
  }

  return { score: Math.min(100, score), signals }
}

// ── Groq LLM deepfake reasoning ───────────────────────────────────────────────

async function analyzeWithGroq(transcript, title, authorName, localSignals) {
  const key = process.env.GROQ_API_KEY
  if (!key || key === 'your_groq_api_key_here') return null

  const transcriptSample = transcript.slice(0, 3000)
  const signalContext    = localSignals.length > 0
    ? `Pre-detected signals: ${localSignals.join(', ')}`
    : 'No pre-detected signals.'

  const prompt = [
    'You are a media forensics expert specializing in AI-generated content detection.',
    'Analyze the following YouTube video transcript and metadata for signs of AI generation.',
    'Respond with ONLY valid JSON (no markdown, no extra text):',
    '{',
    '  "ai_generated_probability": <integer 0-100>,',
    '  "deepfake_risk": "<exactly one of: low | medium | high>",',
    '  "detection_reasons": ["<reason 1>", "<reason 2>", "<reason 3>"],',
    '  "voice_authenticity": "<exactly one of: likely_human | uncertain | likely_synthetic>",',
    '  "reasoning": "<2-3 sentence explanation of the authenticity assessment>",',
    '  "credibility_penalty": <integer 0-20>',
    '}',
    '',
    'SCORING GUIDE for ai_generated_probability:',
    '  0-20:  Almost certainly human-created content',
    '  21-40: Mostly human, minor AI assistance possible',
    '  41-60: Uncertain — mixed signals',
    '  61-80: Likely AI-generated or heavily AI-assisted',
    '  81-100: Almost certainly AI-generated or deepfake',
    '',
    'DETECTION REASONS to check (list only those present):',
    '  - SYNTHETIC_SPEECH_PATTERNS (unnaturally smooth, no disfluencies)',
    '  - SCRIPTED_CONTENT (overly formal, no natural conversation)',
    '  - CLONED_VOICE_INDICATORS (robotic cadence, uniform pitch)',
    '  - AI_GENERATED_SCRIPT (repetitive structure, no personality)',
    '  - DEEPFAKE_VISUAL_INDICATORS (mentioned in transcript)',
    '  - MISSING_HUMAN_ELEMENTS (no laughter, no mistakes, no emotion)',
    '  - SUSPICIOUS_CHANNEL_PATTERNS (new channel, mass-produced content)',
    '  - TRANSCRIPT_INCONSISTENCIES (content contradicts itself)',
    '',
    'CREDIBILITY PENALTY:',
    '  0:    No penalty (clearly human)',
    '  1-8:  Minor (uncertain)',
    '  9-15: Moderate (likely AI-assisted)',
    '  16-20: High (likely AI-generated or deepfake)',
    '',
    signalContext,
    '',
    `Video Title: "${title}"`,
    `Channel: "${authorName}"`,
    '',
    'Transcript sample:',
    transcriptSample,
  ].join('\n')

  try {
    const response = await axios.post(
      GROQ_API_URL,
      {
        model:       GROQ_MODEL,
        messages:    [{ role: 'user', content: prompt }],
        temperature: 0.2,
        max_tokens:  450,
      },
      {
        headers: {
          'Authorization': 'Bearer ' + key,
          'Content-Type':  'application/json',
        },
        timeout: 12000,
      }
    )

    const raw     = response.data.choices[0].message.content.trim()
    const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()
    const parsed  = JSON.parse(cleaned)

    const VALID_RISK  = ['low', 'medium', 'high']
    const VALID_VOICE = ['likely_human', 'uncertain', 'likely_synthetic']

    return {
      aiGeneratedProbability: Math.min(100, Math.max(0, Number(parsed.ai_generated_probability) || 0)),
      deepfakeRisk:           VALID_RISK.includes(parsed.deepfake_risk)   ? parsed.deepfake_risk   : 'low',
      detectionReasons:       Array.isArray(parsed.detection_reasons)
        ? parsed.detection_reasons.slice(0, 6).map(r => String(r))
        : [],
      voiceAuthenticity:      VALID_VOICE.includes(parsed.voice_authenticity) ? parsed.voice_authenticity : 'uncertain',
      reasoning:              String(parsed.reasoning || '').slice(0, 500),
      credibilityPenalty:     Math.min(20, Math.max(0, Number(parsed.credibility_penalty) || 0)),
    }
  } catch (err) {
    console.warn('[deepfakeAnalysis] Groq analysis failed:', err.message)
    return null
  }
}

// ── Local heuristic result builder ────────────────────────────────────────────

function buildHeuristicResult(localScore, localSignals) {
  const risk = localScore >= 60 ? 'high' : localScore >= 30 ? 'medium' : 'low'
  const prob = localScore
  const penalty = Math.round(localScore * 0.15)

  return {
    aiGeneratedProbability: prob,
    deepfakeRisk:           risk,
    detectionReasons:       localSignals,
    voiceAuthenticity:      prob >= 50 ? 'likely_synthetic' : prob >= 25 ? 'uncertain' : 'likely_human',
    reasoning:              localSignals.length > 0
      ? `Transcript analysis detected: ${localSignals.join(', ')}. These patterns are associated with AI-generated or TTS content.`
      : 'No significant AI-generation signals detected in the transcript.',
    credibilityPenalty: penalty,
    analysisSource:     'heuristic',
  }
}

// ── Main export ───────────────────────────────────────────────────────────────
/**
 * Analyzes a video for AI-generation and deepfake signals.
 * Always returns a result — never throws (fails silently).
 *
 * @param {string} videoUrl
 * @param {string} transcript  — already extracted transcript text
 * @returns {{
 *   aiGeneratedProbability: number,
 *   deepfakeRisk: 'low' | 'medium' | 'high',
 *   detectionReasons: string[],
 *   voiceAuthenticity: 'likely_human' | 'uncertain' | 'likely_synthetic',
 *   reasoning: string,
 *   credibilityPenalty: number,
 *   analysisSource: 'groq' | 'heuristic' | 'unavailable'
 * }}
 */
async function analyzeDeepfake(videoUrl, transcript) {
  const EMPTY = {
    aiGeneratedProbability: 0,
    deepfakeRisk:           'low',
    detectionReasons:       [],
    voiceAuthenticity:      'likely_human',
    reasoning:              '',
    credibilityPenalty:     0,
    analysisSource:         'unavailable',
  }

  try {
    if (!transcript || transcript.length < 50) return EMPTY

    // Run local heuristic and metadata fetch in parallel
    const [localResult, meta] = await Promise.all([
      Promise.resolve(analyzeTranscriptPatterns(transcript)),
      fetchVideoMetadata(videoUrl),
    ])

    const title      = meta?.title      || ''
    const authorName = meta?.authorName || ''

    // Try Groq with local signals as context
    const groqResult = await analyzeWithGroq(transcript, title, authorName, localResult.signals)

    if (groqResult) {
      // Merge: if local heuristic found strong signals, boost the Groq score slightly
      const boostedProb = localResult.score > 40
        ? Math.min(100, Math.round(groqResult.aiGeneratedProbability * 0.7 + localResult.score * 0.3))
        : groqResult.aiGeneratedProbability

      // Merge detection reasons (deduplicate)
      const allReasons = [...new Set([...groqResult.detectionReasons, ...localResult.signals])]

      return {
        ...groqResult,
        aiGeneratedProbability: boostedProb,
        detectionReasons:       allReasons.slice(0, 6),
        analysisSource:         'groq',
      }
    }

    // Heuristic fallback
    return buildHeuristicResult(localResult.score, localResult.signals)
  } catch (err) {
    console.warn('[deepfakeAnalysis] analyzeDeepfake failed silently:', err.message)
    return EMPTY
  }
}

module.exports = { analyzeDeepfake }
